const { PNG } = require("pngjs");

const COLORS = {
  background: [18, 26, 40, 255],
  card: [30, 42, 60, 255],
  text: [240, 245, 252, 255],
  mutedText: [150, 168, 190, 255],
  accent: [40, 167, 255, 255],
  accentSoft: [90, 200, 255, 255],
  success: [55, 200, 135, 255],
  warning: [245, 180, 50, 255],
  danger: [235, 90, 90, 255],
  border: [55, 70, 95, 255]
};

const DIGITS = {
  "0": ["111", "101", "101", "101", "111"],
  "1": ["010", "110", "010", "010", "111"],
  "2": ["111", "001", "111", "100", "111"],
  "3": ["111", "001", "111", "001", "111"],
  "4": ["101", "101", "111", "001", "001"],
  "5": ["111", "100", "111", "001", "111"],
  "6": ["111", "100", "111", "101", "111"],
  "7": ["111", "001", "001", "001", "001"],
  "8": ["111", "101", "111", "101", "111"],
  "9": ["111", "101", "111", "001", "111"],
  ".": ["000", "000", "000", "010", "010"],
  "%": ["101", "001", "010", "100", "101"],
  "-": ["000", "000", "111", "000", "000"],
  "+": ["000", "010", "111", "010", "000"],
  "$": ["010", "111", "110", "011", "111"],
  ",": ["000", "000", "000", "010", "100"]
};

function createReportPng(payload) {
  const width = payload.width || 1200;
  const height = payload.height || 630;
  const png = new PNG({ width, height });

  fillRect(png, 0, 0, width, height, COLORS.background);
  drawHeader(png, payload, width);
  drawMetricCards(png, payload.metrics || [], width);
  drawBarChart(png, payload.chart || [], width, height);

  return PNG.sync.write(png);
}

function drawHeader(png, payload, width) {
  const title = payload.title || "Report";
  const subtitle = payload.subtitle || "Generated by API";

  drawText(png, 56, 40, title.toUpperCase(), COLORS.text, 3);
  drawText(png, 56, 92, subtitle.toUpperCase(), COLORS.mutedText, 2);

  drawText(png, width - 320, 42, "STATUS", COLORS.mutedText, 2);
  drawText(
    png,
    width - 320,
    86,
    (payload.status || "OK").toUpperCase(),
    statusColor(payload.status),
    3
  );
}

function drawMetricCards(png, metrics, width) {
  const safeMetrics = metrics.slice(0, 4);
  const startX = 56;
  const topY = 150;
  const gap = 18;
  const cardWidth = Math.floor((width - startX * 2 - gap * 3) / 4);
  const cardHeight = 130;

  for (let i = 0; i < 4; i += 1) {
    const x = startX + i * (cardWidth + gap);
    fillRect(png, x, topY, cardWidth, cardHeight, COLORS.card);
    strokeRect(png, x, topY, cardWidth, cardHeight, COLORS.border);

    const metric = safeMetrics[i] || {
      label: `METRIC ${i + 1}`,
      value: "0",
      trend: "0%"
    };

    drawText(png, x + 16, topY + 16, String(metric.label).toUpperCase(), COLORS.mutedText, 2);
    drawText(png, x + 16, topY + 58, String(metric.value), COLORS.text, 3);
    drawText(png, x + 16, topY + 96, String(metric.trend), trendColor(metric.trend), 2);
  }
}

function drawBarChart(png, chart, width, height) {
  const left = 56;
  const top = 320;
  const chartWidth = width - left * 2;
  const chartHeight = height - top - 56;

  fillRect(png, left, top, chartWidth, chartHeight, COLORS.card);
  strokeRect(png, left, top, chartWidth, chartHeight, COLORS.border);
  drawText(png, left + 16, top + 16, "PERFORMANCE", COLORS.mutedText, 2);

  const safeChart = chart.length ? chart.slice(0, 8) : [{ label: "NO DATA", value: 0 }];
  const maxValue = Math.max(...safeChart.map((item) => Number(item.value) || 0), 1);
  const padding = 16;
  const barAreaTop = top + 52;
  const barAreaHeight = chartHeight - 70;
  const slotWidth = (chartWidth - padding * 2) / safeChart.length;

  safeChart.forEach((item, index) => {
    const value = Number(item.value) || 0;
    const barHeight = Math.max(2, Math.floor((value / maxValue) * (barAreaHeight - 25)));
    const barWidth = Math.max(10, Math.floor(slotWidth * 0.55));
    const x = Math.floor(left + padding + index * slotWidth + (slotWidth - barWidth) / 2);
    const y = top + chartHeight - 16 - barHeight;

    fillRect(png, x, y, barWidth, barHeight, COLORS.accent);
    drawText(png, x, y - 26, String(value), COLORS.accentSoft, 2);
    drawText(png, x, top + chartHeight - 14, truncateLabel(String(item.label)), COLORS.mutedText, 1);
  });
}

function drawText(png, x, y, text, color, scale = 2) {
  let cursorX = x;
  const safeText = String(text || "");

  for (const char of safeText) {
    if (char === " ") {
      cursorX += scale * 4;
      continue;
    }

    const glyph = DIGITS[char] || DIGITS[char.toUpperCase()] || alphaFallback(char);

    if (!glyph) {
      cursorX += scale * 4;
      continue;
    }

    for (let row = 0; row < glyph.length; row += 1) {
      for (let col = 0; col < glyph[row].length; col += 1) {
        if (glyph[row][col] === "1") {
          fillRect(png, cursorX + col * scale, y + row * scale, scale, scale, color);
        }
      }
    }

    cursorX += (glyph[0].length + 1) * scale;
  }
}

function alphaFallback(char) {
  if (/[A-Z]/.test(char.toUpperCase())) {
    return ["111", "101", "111", "101", "101"];
  }
  return null;
}

function fillRect(png, x, y, w, h, color) {
  for (let py = Math.max(0, y); py < Math.min(png.height, y + h); py += 1) {
    for (let px = Math.max(0, x); px < Math.min(png.width, x + w); px += 1) {
      setPixel(png, px, py, color);
    }
  }
}

function strokeRect(png, x, y, w, h, color) {
  fillRect(png, x, y, w, 1, color);
  fillRect(png, x, y + h - 1, w, 1, color);
  fillRect(png, x, y, 1, h, color);
  fillRect(png, x + w - 1, y, 1, h, color);
}

function setPixel(png, x, y, [r, g, b, a]) {
  const idx = (png.width * y + x) << 2;
  png.data[idx] = r;
  png.data[idx + 1] = g;
  png.data[idx + 2] = b;
  png.data[idx + 3] = a;
}

function trendColor(trend) {
  const value = String(trend || "").trim();
  if (value.startsWith("+")) return COLORS.success;
  if (value.startsWith("-")) return COLORS.danger;
  return COLORS.warning;
}

function statusColor(status) {
  const normalized = String(status || "").toLowerCase();
  if (["ok", "good", "healthy", "success"].includes(normalized)) return COLORS.success;
  if (["warning", "warn", "attention"].includes(normalized)) return COLORS.warning;
  if (["error", "down", "critical", "failed"].includes(normalized)) return COLORS.danger;
  return COLORS.accentSoft;
}

function truncateLabel(label) {
  return label.length <= 6 ? label.toUpperCase() : `${label.slice(0, 6).toUpperCase()}`;
}

module.exports = {
  createReportPng
};
